name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: [ ubuntu-latest ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: true
#
#      - name: Setup .NET SDK
#        uses: actions/setup-dotnet@v4

      - name: Build, Test and Package
        run: |
          chmod +x ./build.sh
          ./build.sh Tests Pack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./output/packages